x=imread('C:\Users\deepthi\Desktop\Bio\images.jpg');
x=im2double(x);
figure
imshow(x);
red=x(:,:,1);
figure
imshow(red);
title('red')
colorbar
gre=x(:,:,2);
figure
imshow(gre);
title('green')
colorbar
blu=x(:,:,3);
figure
imshow(blu);
title('blue')
colorbar
VI=(red-blu)./(red+blu);
figure
imshow(VI);
title('VI')
colorbar